#!/usr/bin/env bash
# Generate the "Shadow" desktop theme from theme/palette.sh.
#
# The theme is GENERATED, not hand-drawn: change a colour in palette.sh, re-run
# this, and the GTK CSS, the xfwm4 window decorations and the terminal scheme
# all move together. That property is the reason this is worth open-sourcing —
# it is a palette plus a builder, not 4,000 lines of CSS nobody can re-tint.
#
#   build-theme.sh [OUTDIR]     default: theme/build/Shadow
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=palette.sh
. "${HERE}/palette.sh"

OUT="${1:-${HERE}/build/${SHADOW_NAME}}"
command -v magick >/dev/null 2>&1 || command -v convert >/dev/null 2>&1 \
  || { echo "ImageMagick (magick/convert) required for the xfwm4 assets" >&2; exit 1; }
IM="$(command -v magick || command -v convert)"
im() { if [[ "$IM" == *magick ]]; then "$IM" "$@"; else "$IM" "$@"; fi; }

rm -rf "$OUT"
mkdir -p "$OUT"/{gtk-3.0,gtk-4.0,xfwm4}

# ------------------------------------------------------------------ index ----
cat > "${OUT}/index.theme" <<INDEX
[Desktop Entry]
Type=X-GNOME-Metatheme
Name=${SHADOW_NAME}
Comment=Dark, opaque, discreet. Shadow Software's desktop look.
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=${SHADOW_NAME}
MetacityTheme=${SHADOW_NAME}
IconTheme=Papirus-Dark
CursorTheme=Adwaita
ButtonLayout=:minimize,maximize,close
INDEX

# -------------------------------------------------------------------- GTK ----
# Thin by design: GTK's own dark stylesheet does the widget drawing, and Shadow
# re-tints it through named colours. A full re-implementation would look the
# same and rot the first time GTK changes a selector.
gtk_css() { # $1 = gtk version resource path
cat <<CSS
/* ${SHADOW_NAME} — generated by theme/build-theme.sh. Do not edit by hand;
   edit theme/palette.sh and rebuild. */
@import url("resource://${1}");

@define-color theme_bg_color ${SHADOW_BG_1};
@define-color theme_base_color ${SHADOW_BG_0};
@define-color theme_fg_color ${SHADOW_FG};
@define-color theme_text_color ${SHADOW_FG};
@define-color theme_selected_bg_color ${SHADOW_ACCENT_DIM};
@define-color theme_selected_fg_color ${SHADOW_BG_0};
@define-color insensitive_fg_color ${SHADOW_FG_MUTE};
@define-color insensitive_bg_color ${SHADOW_BG_2};
@define-color borders ${SHADOW_BG_4};
@define-color unfocused_borders ${SHADOW_BG_3};
@define-color warning_color ${SHADOW_WARN};
@define-color error_color ${SHADOW_ERROR};
@define-color success_color ${SHADOW_OK};
@define-color accent_color ${SHADOW_ACCENT};
@define-color accent_bg_color ${SHADOW_ACCENT_DIM};
@define-color accent_fg_color ${SHADOW_BG_0};
@define-color window_bg_color ${SHADOW_BG_1};
@define-color window_fg_color ${SHADOW_FG};
@define-color view_bg_color ${SHADOW_BG_0};
@define-color view_fg_color ${SHADOW_FG};
@define-color headerbar_bg_color ${SHADOW_BG_2};
@define-color headerbar_fg_color ${SHADOW_FG};
@define-color card_bg_color ${SHADOW_BG_2};
@define-color popover_bg_color ${SHADOW_BG_2};
@define-color sidebar_bg_color ${SHADOW_BG_1};

/* Opaque, always: translucency is what makes a dark desktop look muddy over a
   bright window behind it. */
window, .background, popover > contents, menu, .csd .titlebar {
  background-color: ${SHADOW_BG_1};
  color: ${SHADOW_FG};
}
headerbar, .titlebar { background-image: none; background-color: ${SHADOW_BG_2}; }

/* Accent as glow, never as fill: it edges the focused thing, it does not
   flood it (THE-ESSENCE.md section 6). */
:focus-visible, entry:focus, button:focus {
  outline: 1px solid ${SHADOW_ACCENT};
  outline-offset: -1px;
}
entry:focus, spinbutton:focus { border-color: ${SHADOW_ACCENT}; box-shadow: none; }
progressbar > trough > progress, levelbar block.filled { background-color: ${SHADOW_ACCENT_DIM}; }
check:checked, radio:checked, switch:checked { background-color: ${SHADOW_ACCENT_DIM}; }
selection, ::selection { background-color: ${SHADOW_ACCENT_DIM}; color: ${SHADOW_BG_0}; }
CSS
}
gtk_css "/org/gtk/libgtk/theme/Adwaita/gtk-contained-dark.css" > "${OUT}/gtk-3.0/gtk.css"
gtk_css "/org/gtk/libgtk/theme/Default/Default-dark.css"       > "${OUT}/gtk-4.0/gtk.css"
cp "${OUT}/gtk-3.0/gtk.css" "${OUT}/gtk-3.0/gtk-dark.css"

# ------------------------------------------------------------------ xfwm4 ----
# xfwm4 draws window frames from PNGs, so the decorations are generated from the
# same palette rather than shipped as opaque binary art.
TITLE_H="${SHADOW_TITLE_H:-28}"
BORDER="${SHADOW_BORDER:-1}"
# Buttons MUST be exactly as tall as the title bar. xfwm4 derives each button's
# clickable box from its image, so a 16px button in a 28px title bar draws in
# the right place and takes clicks in the wrong one — which is how a close
# button ends up doing nothing.
BTN="$TITLE_H"

# Frame assets are fully opaque, always. See the note on SHADOW_ALPHA in
# palette.sh: partial alpha here makes xfwm4 shape the frame's input region
# away, and the title bar silently stops accepting clicks.
A="FF"

strip() { # $1 out, $2 w, $3 h, $4 colour (#rrggbb — alpha is appended)
  im -size "${2}x${3}" "xc:${4}${A}" -alpha set -define png:color-type=6 \
    "PNG32:${OUT}/xfwm4/${1}"
}

# Title bar segments 1..5: xfwm4 tiles these across the title. One flat colour
# each keeps it opaque and free of the gradient banding a dark theme shows up.
for state in active inactive; do
  # The title ground is the SAME colour as the app content below it. Any
  # difference here is what shows up as a seam.
  case "$state" in
    active)   tbg="$SHADOW_BG_2"; frame="$SHADOW_BG_2" ;;
    inactive) tbg="$SHADOW_BG_1"; frame="$SHADOW_BG_1" ;;
  esac
  for n in 1 2 3 4 5; do strip "title-${n}-${state}.png" 1 "$TITLE_H" "$tbg"; done
  strip "top-left-${state}.png"     "$BORDER" "$TITLE_H" "$tbg"
  strip "top-right-${state}.png"    "$BORDER" "$TITLE_H" "$tbg"
  strip "left-${state}.png"         "$BORDER" 1 "$frame"
  strip "right-${state}.png"        "$BORDER" 1 "$frame"
  strip "bottom-${state}.png"       1 "$BORDER" "$frame"
  strip "bottom-left-${state}.png"  "$BORDER" "$BORDER" "$frame"
  strip "bottom-right-${state}.png" "$BORDER" "$BORDER" "$frame"
done

# Buttons: a glyph in ink on a title-coloured ground, the close button carrying
# the only accent on the frame so the destructive action is what your eye lands
# on. The ground matches the title strip exactly — a transparent button over a
# translucent title would double the alpha and show as a lighter square.
button_glyph() { # $1 name, $2 glyph-draw, $3 colour, $4 state, $5 ground
  im -size "${BTN}x${BTN}" "xc:${5}${A}" -alpha set \
    -stroke "$3" -strokewidth 1.4 -fill none -draw "$2" \
    -define png:color-type=6 "PNG32:${OUT}/xfwm4/${1}-${4}.png"
}
# Glyphs are inset from the button edge so a 28px button still reads as a small
# mark rather than filling the title bar.
inset=$(( BTN / 3 ))
half=$((BTN / 2)); pad=$inset; far=$((BTN - inset))
for state_pair in "active:${SHADOW_FG}:${SHADOW_BG_2}" "inactive:${SHADOW_FG_MUTE}:${SHADOW_BG_1}" \
                  "prelight:${SHADOW_ACCENT}:${SHADOW_BG_3}" "pressed:${SHADOW_ACCENT_DIM}:${SHADOW_BG_3}"; do
  st="${state_pair%%:*}"; rest="${state_pair#*:}"; col="${rest%%:*}"; ground="${rest##*:}"
  button_glyph close    "line ${pad},${pad} ${far},${far} line ${far},${pad} ${pad},${far}" \
               "$( [[ $st == inactive ]] && echo "$col" || echo "$SHADOW_ERROR" )" "$st" "$ground"
  button_glyph maximize "rectangle ${pad},${pad} ${far},${far}" "$col" "$st" "$ground"
  button_glyph hide     "line ${pad},$((far - 1)) ${far},$((far - 1))" "$col" "$st" "$ground"
  button_glyph shade    "line ${pad},${pad} ${half},${far} line ${half},${far} ${far},${pad}" "$col" "$st" "$ground"
  button_glyph stick    "circle ${half},${half} ${half},$((half - 3))" "$col" "$st" "$ground"
  button_glyph menu     "line ${pad},${half} ${far},${half}" "$col" "$st" "$ground"
  # xfwm4 asks for toggled variants when a window is maximized or shaded; without
  # them the button silently reverts to the default theme's artwork.
  cp "${OUT}/xfwm4/maximize-${st}.png" "${OUT}/xfwm4/maximize-toggled-${st}.png"
  cp "${OUT}/xfwm4/shade-${st}.png"    "${OUT}/xfwm4/shade-toggled-${st}.png"
  cp "${OUT}/xfwm4/stick-${st}.png"    "${OUT}/xfwm4/stick-toggled-${st}.png"
done

cat > "${OUT}/xfwm4/themerc" <<THEMERC
# ${SHADOW_NAME} — generated by theme/build-theme.sh from theme/palette.sh
#
# No button_layout here on purpose: which buttons appear, and on which side, is
# the user's setting (Settings > Window Manager, stored at xfwm4
# /general/button_layout). A theme that overrides it silently changes something
# the user chose.
button_offset=2
button_spacing=2
full_width_title=true
title_shadow_active=false
title_shadow_inactive=false
title_horizontal_offset=6
title_vertical_offset_active=0
title_vertical_offset_inactive=0
active_text_color=${SHADOW_FG}
inactive_text_color=${SHADOW_FG_DIM}
active_text_shadow_color=${SHADOW_BG_0}
inactive_text_shadow_color=${SHADOW_BG_0}
shadow_delta_height=0
shadow_delta_width=0
shadow_delta_x=0
shadow_delta_y=0
shadow_opacity=40
THEMERC

# --------------------------------------------------------------- terminal ----
mkdir -p "${OUT}/terminal"
palette_csv=""
for c in "${SHADOW_ANSI[@]}"; do palette_csv+="${c};"; done
cat > "${OUT}/terminal/shadow-terminalrc" <<TERMRC
# Shadow — xfce4-terminal settings, generated from theme/palette.sh.
# Merged into ~/.config/xfce4/terminal/terminalrc by ss-shadow-theme.
# BackgroundDarkness is opacity (1.0 = opaque) and MUST equal the frame alpha in
# palette.sh, or the title bar and the shell area will not read as one surface.
[Configuration]
# Without this, xfce4-terminal takes its colours from the GTK theme and every
# Color* key below is silently ignored — which is why the shell background did
# not match the title bar even when both were set to the same hex.
ColorUseTheme=FALSE
BackgroundMode=TERMINAL_BACKGROUND_TRANSPARENT
BackgroundDarkness=${SHADOW_ALPHA}
# Note: with xfwm4 compositing OFF this is pseudo-transparency against the
# wallpaper (always readable); with compositing ON it is real transparency and
# shows the window behind. Set both to 1.0 for a fully opaque look.
ColorForeground=${SHADOW_FG}
ColorBackground=${SHADOW_BG_2}
ColorCursor=${SHADOW_ACCENT}
ColorCursorForeground=${SHADOW_BG_0}
ColorSelection=${SHADOW_BG_3}
ColorSelectionUseDefault=FALSE
ColorBold=${SHADOW_FG}
ColorBoldUseDefault=FALSE
ColorPalette=${palette_csv%;}
# Sleek: no toolbar, no window border of its own, and the scrollbar off the edge.
MiscBordersDefault=TRUE
MiscMenubarDefault=FALSE
MiscToolbarDefault=FALSE
MiscScrollbarDefault=FALSE
MiscShowUnsafePasteDialog=FALSE
ScrollingBar=TERMINAL_SCROLLBAR_NONE
TERMRC

cat > "${OUT}/terminal/shadow.theme" <<TERM
[Scheme]
Name=${SHADOW_NAME}
ColorForeground=${SHADOW_FG}
ColorBackground=${SHADOW_BG_2}
ColorCursor=${SHADOW_ACCENT}
ColorCursorForeground=${SHADOW_BG_0}
ColorSelection=${SHADOW_ACCENT_DIM}
ColorSelectionBackground=${SHADOW_BG_3}
ColorBold=${SHADOW_FG}
ColorPalette=${palette_csv%;}
TERM

cat > "${OUT}/README-generated.txt" <<GEN
${SHADOW_NAME} — generated $(date -u +%Y-%m-%dT%H:%M:%SZ) by theme/build-theme.sh
Palette source: theme/palette.sh (Shadow Software brand, THE-ESSENCE.md section 6)
Do not edit these files; edit the palette and rebuild.
GEN

echo "built ${SHADOW_NAME} → ${OUT}"
find "$OUT" -type f | wc -l | xargs printf '  %s files\n'
